apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-forecast-dynamic
  namespace: load-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-forecast-dynamic
  template:
    metadata:
      labels:
        app: load-forecast-dynamic
    spec:
      containers:
        - name: api
          image: load-forecast-api:v18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "dynamic"
            - name: RETRAINED_MODELS_DIR
              value: "/app/retrained-models"
          volumeMounts:
            - name: model-storage
              mountPath: /app/retrained-models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage
